logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mysql/*Mapper.xml